version: "3.2"
services:
  nodejs:
    build: 
      context: .
    image: samueladdisu/kuriftu-ticket-app
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_USER=sam
      - MYSQL_PASS=18424325
      - MYSQL_DB=lalibela
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "8000:8000"
    container_name: moe-nodejs-app
  mysql:
    image: mysql:8.0
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    container_name: moe-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:8080"
    environment:
      - PMA_HOST=moe-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: moe-phpmyadmin-app
networks:
  frontend:
  backend:
  
